# Generated by Django 3.2.7 on 2021-10-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='social_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='social_github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
