# Generated by Django 3.2.7 on 2021-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimuit', '0006_award_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image_hover',
            field=models.ImageField(blank=True, upload_to='partner/'),
        ),
    ]
