# Generated by Django 3.2.7 on 2021-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimuit', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='demo time', max_length=100),
            preserve_default=False,
        ),
    ]
