# Generated by Django 3.2.7 on 2021-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimuit', '0011_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
