# Generated by Django 3.2.7 on 2021-12-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimuit', '0012_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_details',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
